name: idea_widget_preview
description: Widget Preview in IDEA-based development environments.
version: 2.0.0
homepage: https://github.com/andrasferenczi/idea_widget_preview

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  analyzer: ^6.4.0
  collection: ^1.16.0
  device_frame: ^1.2.0
  flutter_hooks: ^0.20.5
  http: ^1.2.1
  intl: ^0.19.0
  shelf: ^1.3.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
